version: "3.8"

services:
  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "licenseservice"

  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      - "SPRING_PROFILES_ACTIVE=native"
    networks:
      backend:
        aliases:
          - "configserver"

networks:
  backend:
    driver: bridge
