version: "3.8"

services:

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - /envs/database.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  vaultserver:
    image: hashicorp/vault:1.13.3
    ports:
      - "8200:8200"
    env_file:
      - /envs/vault.env
    networks:
      backend:
        aliases:
          - "vaultserver"

  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo 'configserver start up'
        echo "$$(cat /run/secrets/mysec)" >> /app/bootstrap.yml
        echo 'add secret properties'
        java -cp app:app/lib/* com.optimagrowth.configserver.ConfigServerApplication
    ports:
      - "8071:8071"
    env_file:
      - /envs/configserver.env
    secrets:
      - mysec
    networks:
      backend:
        aliases:
          - "configserver"

  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    env_file:
      - /envs/licensing-service.env
    networks:
      backend:
        aliases:
          - "licenseservice"

  eurekaserver:
    image: ostock/eurekaserver:0.0.1-SNAPSHOT
    ports:
      - "8070:8070"
    networks:
      backend:
        aliases:
            - "eurekaserver"

  organizationservice:
    image: ostock/organization-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    env_file:
      - /envs/organization-service.env
    networks:
      backend:
        aliases:
          - "organizationservice"

  gatewayserver:
    image: ostock/gatewayserver:0.0.1-SNAPSHOT
    ports:
      - "8072:8072"
    networks:
      backend:
        aliases:
          - "gatewayserver"

secrets:
  mysec:
    external: true

networks:
  backend:
    driver: overlay
