version: "3.8"

services:

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pass_secret
      POSTGRES_DB:       "ostock_dev"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - pg_pass_secret

  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo 'configserver start up'
        echo "\nencrypt:\n  key: $$(cat /run/secrets/mysec)" >> /app/bootstrap.yml
        java -cp app:app/lib/* com.optimagrowth.configserver.ConfigServerApplication
    ports:
      - "8071:8071"
    environment:
      SPRING_PROFILES_ACTIVE: native, git
    secrets:
      - mysec
    networks:
      backend:
        aliases:
          - "configserver"

  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE:dev
      - SPRING_CLOUD_CONFIG_URI:http://configserver:8071
    networks:
      backend:
        aliases:
          - "licenseservice"

secrets:
  mysec:
    external: true
  pg_pass_secret:
    external: true

networks:
  backend:
    driver: overlay
